# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - algi_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: insecurepassword # We're keeping this local so no real need to change it
      MYSQL_DATABASE: algi

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8083:8080

volumes:
  algi_db:
