    instrument: {
      id: "306245dd-b82d-4d8d-bcc5-7c58e87cdd15",
      url: "https://api.robinhood.com/instruments/306245dd-b82d-4d8d-bcc5-7c58e87cdd15/",
      quote: "https://api.robinhood.com/quotes/VOO/",
      fundamentals: "https://api.robinhood.com/fundamentals/VOO/",
      splits:
        "https://api.robinhood.com/instruments/306245dd-b82d-4d8d-bcc5-7c58e87cdd15/splits/",
      state: "active",
      market: "https://api.robinhood.com/markets/ARCX/",
      simple_name: "Vanguard S&P 500 ETF",
      name: "Vanguard S&P 500 ETF",
      tradeable: true,
      tradability: "tradable",
      symbol: "VOO",
      bloomberg_unique: "EQ0000000011209832",
      margin_initial_ratio: "0.5000",
      maintenance_ratio: "0.2500",
      country: "US",
      day_trade_ratio: "0.2500",
      list_date: "2010-09-09",
      min_tick_size: null,
      type: "etp",
      tradable_chain_id: "147f59d9-43fd-43b0-aef9-2494820e33d5",
      rhs_tradability: "tradable",
      fractional_tradability: "tradable",
      default_collar_fraction: "0.05",
      ipo_access_status: null,
      ipo_access_cob_deadline: null,
      ipo_s1_url: null,
      ipo_roadshow_url: null,
      is_spac: false,
      is_test: false,
      ipo_access_supports_dsp: false,
    },